### ISSUE TITLE
Dinner recipe - "Shrimp Scampi En Papillote" should be the Heading

### ISSUE THREAD

**Issue by diane-seethor** [IntroToCode/CodeMates8_Fall22#17]
## 💬 Discussion topic

Text

## ❗ Potential issues

Text

## 👥 People to consult

Text

## 📃 Details

Text

**Comment by isaacmcastro94** [comment]
Agreed! Let me make that change now!

**Comment by isaacmcastro94** [comment]
Pull request made!
