### ISSUE TITLE
Plant-based bacon for vegans

### ISSUE THREAD

**Issue by diane-seethor** [IntroToCode/CodeMates8_Fall22#22]
## 💬 Discussion topic

We want to ensure vegans get to enjoy our breakfast recipe as well, so we will be adding alternatives to bacon that are vegan-friendly.

## ❗ Potential issues

As we will be combining 2 recipes (default bacon recipe and vegan-friendly recipe) onto a single webpage, we will have to ensure it is readable and understandable by both audiences.

## 👥 People to consult

@bhl212 

## 📃 Details

Acceptance criteria:

- When a user hovers over the word "bacon", a tooltip should appear to say "or vegan bacon"
- This should apply for every instance of the word "bacon" on the page

**Comment by isaacmcastro94** [comment]
Love this idea!! Thanks for taking care of this!

**Comment by bhl212** [comment]
Great point @diane-seethor! Dietary restrictions are important to note.
