### ISSUE TITLE
Additional details for the equipment re: scampi recipe needed!

### ISSUE THREAD

**Issue by isaacmcastro94** [IntroToCode/CodeMates8_Fall22#5]
## 💬 Discussion topic

Text

## ❗ Potential issues

Text

## 👥 People to consult

@yiannosv Can you review & make any necessary changes to the equipment section?

## 📃 Details

Text

**Comment by yiannosv** [comment]
On it

**Comment by yiannosv** [comment]
I added equipment and made a pull request for this. Please approve!
