### ISSUE TITLE
Fio's commit has a merge issue!

### ISSUE THREAD

**Issue by isaacmcastro94** [IntroToCode/CodeMates8_Fall22#6]
## 💬 Discussion topic

Text

## ❗ Potential issues
Not sure what the problem is, but I can't approve Fio's merge request. 
Text

## 👥 People to consult

Text

## 📃 Details

Text

**Comment by bhl212** [comment]
Yeah.. not sure about this one.

**Comment by isaacmcastro94** [comment]
Resolved!!
