### ISSUE TITLE
Add photo for shrimp scampi!!

### ISSUE THREAD

**Issue by isaacmcastro94** [IntroToCode/CodeMates8_Fall22#9]
## 💬 Discussion topic

Text
I'm going to add a new photo for the shrimp scampi

## ❗ Potential issues

Text

## 👥 People to consult

Text

## 📃 Details
![image](https://user-images.githubusercontent.com/114119481/197929676-2c47e3e7-3472-4a41-8a25-f1aa6e9fe1e1.png)

Text

**Comment by bhl212** [comment]
Isaac crushing it w/ these pics. LGTM! @yiannosv could you approve?
